name: MooCountdown
author: web_innovation
category: Realtime
tags: [animation]
#docs: http://web-innovation.fr/blog/?p=239
#demo: http://www.web-innovation.fr/blog/tutos/mootools/mooCountdown/
#current: 0.1